<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit7285711e24f7dc583ad0a2aaa32a3f90
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OProfile\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OProfile\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'AltoRouter' => __DIR__ . '/..' . '/altorouter/altorouter/AltoRouter.php',
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit7285711e24f7dc583ad0a2aaa32a3f90::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit7285711e24f7dc583ad0a2aaa32a3f90::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit7285711e24f7dc583ad0a2aaa32a3f90::$classMap;

        }, null, ClassLoader::class);
    }
}
