<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit62a079c5bdab1159333ffb4ccf0f7b1a
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OProfile\\' => 9,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OProfile\\' => 
        array (
            0 => __DIR__ . '/../..' . '/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit62a079c5bdab1159333ffb4ccf0f7b1a::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit62a079c5bdab1159333ffb4ccf0f7b1a::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit62a079c5bdab1159333ffb4ccf0f7b1a::$classMap;

        }, null, ClassLoader::class);
    }
}
